# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Adrien Folie
tagline:          'Software Engineer'
description:      'Software Engineer, passionate about new technology'
url:              http://blog.foliea.io
baseurl:          /

author:
  name:           'Adrien Folie'
  url:            http://www.foliea.io
  github:         https://github.com/foliea
  twitter:        https://twitter.com/foliea

paginate:         5

# Custom vars
version:          0.1.0

github:           https://github.com/foliea/foliea.github.io
