# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Adrien Folie
year:             2016
tagline:          'Software Engineer'
description:      'Software Engineer, passionate about new technology'
url:              http://foliea.github.io/
baseurl:          /

author:
  name:           'Adrien Folie'
  url:            http://foliea.com
  github:         https://github.com/foliea
  twitter:        https://twitter.com/folieadrien

paginate:         5

# Custom vars
version:          0.1.0

github:           https://github.com/foliea/foliea.github.io
